config {
    type: "table",
    name: "movies_details2",
    description: "create movie table with all required details",
    columns: {
        movie_name: "title of the movie",
        IMDB_Rating: "rating of the movie",
        Genre: "genre of the movie",
        cast_names: "cast name"
    }
}


 SELECT movie_name, IMDB_Rating, Genre,
 CONCAT(Star1, ',', Star2, ',', Star3, ',', Star4) AS cast_names
 from imdb_dataset.imdb_details  

